name: data-pipeline

on:
	schedule:
		- cron: '0 6 * * *'
	workflow_dispatch: {}

permissions:
	contents: write

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v4
				with:
					persist-credentials: true

			- name: Use Node.js
				uses: actions/setup-node@v4
				with:
					node-version: '18'

			- name: Install
				run: npm ci

			- name: Run scraping
				env:
					LISTING_START_URLS: ${{ secrets.LISTING_START_URLS }}
				run: npm run scrape

			- name: Run cleaning
				run: npm run clean

			- name: Validate dataset
				run: node scripts/validate.js

			- name: Commit dataset (if changed)
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
				run: |
					git config user.name "github-actions[bot]"
					git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
					git add data/dataset.csv || true
					if git diff --staged --quiet; then
						echo "no changes to commit"
					else
						git commit -m "chore(data): update dataset.csv [skip ci]"
						git push
					fi

